config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root 'tasks#index'
  resources :tasks
  resources :menus, only: %i[ index ]
  resource :profiles, only: %i[ edit update ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  enum repeat: { nothing: 1, daily: 2, weekly: 3, monthly: 4, year: 5 }
  enum status: { incomplete: 0, complete: 1 }
  scope :recent, -> { order(craeted_at: desc)}

  # 検索方法分岐
  def self.search(keyword, search_method)
    @tasks = Task.all
    return @tasks unless keyword.present?
      if search_method == "perfect_match"
        @tasks = @tasks.where("title LIKE?", "#{keyword}")
      elsif search_method == "forward_match"
        @tasks = @tasks.where("title LIKE?","#{keyword}%")
      elsif search_method == "backward_match"
        @tasks = @tasks.where("title LIKE?","%#{keyword}")
      elsif search_method == "partial_match"
        @tasks = @tasks.where("title LIKE?","%#{keyword}%")
      end
    @tasks
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/menus_controller.rb
class MenusController < BaseController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < BaseController
  def edit
  end

  def update
    current_user.password = user_params[:password]
    if current_user.save
      redirect_to :new_user_session, notice: 'パスワードを変更した為、ログアウトしました'
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < BaseController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.search(params[:keyword], params[:search_method]).page(params[:page]).per(10)
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice:"タスク登録が出来ました！！"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクが更新できました！！"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to task_url, notice: "タスクが削除できました！！"
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :start_at, :end_at, :repeat, :place, :content, :category_id, :status)
  end

end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
    redirect_to tasks_path if user_signed_in?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  layout 'signup'

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'login'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/layouts/_footer.html.erb
<footer class="relative bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">TODO App by Ruby on Rails & Bootstrap 5</div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed navbar navbar-fixed-top navbar-inverse navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "ToDoapp", root_path, id: "logo" %>
    <nav>
      <%= link_to "Menu", menus_path, method: :get %>
      <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class= "fixed2">
    <div class="container">
      <%= yield %>
    </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body class = "box center">
    <%= yield %>
  </body>

</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "box center">
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
<h1>メニュー</h1>

<div class="box">
  <%= link_to "・タスク一覧", tasks_path %>
  <br>
  <%= link_to "・パスワード変更", edit_profiles_path %>
  <br>
  <%= link_to "・ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
</div>

app/views/profiles/edit.html.erb
<h2>パスワード変更</h2>

<%= form_with(model: current_user, url: profiles_path) do |f| %>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "新しいパスワード" %>
  </div>

  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>

<%= link_to "戻る", :back %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="box">
      <%= form.label :タイトル, style: "display: inline" %>
      <%= form.text_field :title, :size => "110x1" %>
      <%= form.label :status, 'ステータス' %>
      <%= form.collection_select :status, Task.statuses_i18n, :first, :last %>
    <hr>
    <div class="row">
      <div class="col">
      <%= form.label :開始日時, style: "display: inline" %>
      <%= form.datetime_field :start_at %>
      </div>
      <div class="col">
      <%= form.label :終了日時, style: "display: inline" %>
      <%= form.datetime_field :end_at %>
      </div>
      <div class="col">
      <%= form.label :repeat, '繰返し' %>
      <%= form.collection_select :repeat, Task.repeats_i18n, :first, :last, prompt: '選択してください' %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
      <%= form.label :category_id, 'カテゴリ' %>
      <%= form.collection_select :category_id, Category.all, :id, :name, prompt: '選択してください' %>
      </div>
      <div class="col">
      <%= form.label :場所, style: "display: inline" %>
      <%= form.text_field :place %>
      </div>
    </div>
    <hr>
      <%= form.label :詳細, style: "display: inline-block" %>
      <%= form.text_area :content, :size => "100x4" %>
    <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="box">
<div id="<%= dom_id task %>">
  <p>
    <strong>Title：</strong>
    <%= task.title %>
  </p>
  <hr>
  <p>
  <div class="row">
    <div class="col-sm-5">
    <strong>開始日時：</strong>
    <%= task.start_at %>
    </div>
    <div class="col-sm-5">
    <strong>終了日時：</strong>
    <%= task.end_at %>
    </div>
    <div class="col-sm-2">
    <strong>完了</strong>
    <%= task.status_i18n %>
    </div>
  </div>
  </p>
  <hr>
  <p>
  <div class="row">
    <div class="col">
    <strong>詳細:</strong>
    <%= task.content %>
    </div>
    <div class="col">
    <strong>カテゴリ:</strong>
    <%= task.category&.name %>
    </div>
  </div>
  </p>
  <hr>
  <p>
  <div class="row justify-content-end">
    <div class="col-3">
    <strong>登録日時:</strong>
    <%= l task.created_at, format: :long %>
    </div>
    <div class="col-3">
    <strong>更新日時:</strong>
    <%= l task.updated_at, format: :long %>
    </div>
  </div>
  </p>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "一覧に戻る", tasks_path, class: 'btn btn-outline-primary' %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>タスク一覧</h1>

<div class="search_form">
  <%= form_with url: tasks_path, method: :get do |f| %>
    <%= f.text_field :keyword, :size => "60x1" %>
    <%= f.select :search_method, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

  <%= link_to "＋新しいタスクを追加", new_task_path %>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
  <div class="row justify-content-end">
    <p>
    <div class="col-1">
      <%= link_to "編集", edit_task_path(task), class: 'btn btn-outline-primary' %>
    </div>
    <div class="col-1">
      <%= button_to "削除", task, method: :delete, class: 'btn btn-outline-primary' %>
    </div>
    </p>
  </div>
  <% end %>
</div>

  <div class="paginate">
    <%= paginate @tasks %>
  </div>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "一覧に戻る", tasks_path, class: 'btn btn-outline-primary' %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>